In [2]:
import numpy as np
 
arr = [1,2,3,4]        #python list
numpy_arr = np.array(arr)    #numpy array
numpy_arr

array([1, 2, 3, 4])

In [11]:
# Two-Dimensional array
import numpy as np

arr = [[1,2,3,4],[4,5,6,7]]
numpy_arr = np.array(arr)
print(numpy_arr[0][0],numpy_arr[0][1],numpy_arr[0][3],numpy_arr[1][3])

1 2 4 7


In [23]:
# Three-Dimensional array
arr = [[[1,2,3,4],[4,5,6,7],[7,8,9,10]]]
numpy_arr = np.array(arr)
print("1st column, 1st row -", numpy_arr[0][0][0])
print("2nd column, 3rd row -", numpy_arr[0][1][2])
print("4th column, 4th row -", numpy_arr[0][2][3])
print("1st column, 1st row -", numpy_arr[0,1,3])
print(numpy_arr)

1st column, 1st row - 1
2nd column, 3rd row - 6
4th column, 4th row - 10
1st column, 1st row - 7
[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]]


In [32]:
arr = [[[1,2,3,4],[4,5,6,7],[7,8,9,10]],[[11,12,13,14],[14,15,16,17],[17,18,19,20]]]
numpy_arr = np.array(arr)
print(numpy_arr)
print("1st column, 1st row -", numpy_arr[1][1][3])
# print("2nd column, 3rd row -", numpy_arr[0][1][2])
# print("4th column, 4th row -", numpy_arr[0][2][3])
# print("1st column, 1st row -", numpy_arr[0,1,3])

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]

 [[11 12 13 14]
  [14 15 16 17]
  [17 18 19 20]]]
1st column, 1st row - 17


In [34]:
# 6. How do you find the data type of the elements stored in the NumPy arrays?
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array(['I', 'love', 'Interviewbit'])    # Stored as Unicode characters with length of characters ranging from 1 to 12
arr3 = np.array([1, 2, 3, 4], dtype='S')        # Creating numpy array of defined type string

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int32
<U12
|S1


In [37]:
# 7. How can you reverse a NumPy array?
import numpy as np

# create numpy array
arr = np.array([1, 2, 4, 6])

# To reverse array
reverse_arr = arr[::-1]
print(reverse_arr)

[6 4 2 1]


In [38]:
# 
# Method 2: flipud function: This function is provided by NumPy to reverse the NumPy array. Let us see the below example about its usage.


import numpy as np

# create numpy array
arr = np.array([1, 2, 4, 5, 6])

#flipud method for reversing
reverse_arr = np.flipud(arr)
print(reverse_arr)

[6 5 4 2 1]


# 8. How is np.mean() different from np.average() in NumPy?
    np.mean() method calculates the arithmetic mean and provides additional options for input and results. For example, it has the option to specify what data types have to be taken, where the result has to be placed etc.
    np.average() computes the weighted average if the weights parameter is specified. In the case of weighted average, instead of considering that each data point is contributing equally to the final average, it considers that some data points have more weightage than the others (unequal contribution).

In [47]:
import numpy as np
arr = np.array([1, 2, 1, 3, 5, 0, 0, 0, 2, 3])
result = np.mean(arr)
print(result)

1.7


In [48]:
result = np.average(arr)
print(result)

1.7


# 9. How do you count the frequency of a given positive value appearing in the NumPy array?
    We can make use of the bincount() function to compute the number of times a given value is there in the array. This function accepts only positive integers and boolean expressions as the arguments.

In [42]:
import numpy as np
arr = np.array([1, 2, 1, 3, 5, 0, 0, 0, 2, 3])
result = np.bincount(arr)
print(result)

[3 2 2 2 0 1]
